name: Conventional Commits PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  conventional_commits_pr_title_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR title
        run: |
          title=$(echo "${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')
          if [[ $title =~ ^(build|ci|chore|docs|feat|feature|fix|perf|refactor|revert|style|test)\([a-zA-Z0-9_-]+\):\ .+ ]]; then
            echo "PR title follows Conventional Commits rules."
            exit 0
          else
            echo "PR title does not follow Conventional Commits rules."
            exit 1
          fi
